:compat-mode:
= Lab 5 - Deploy a .NET Application

In this lab we'll deploy an ASP.NET v5 application to Cloud Foundry, and run it inside of a linux container using the .NET CoreCLR. 

. Use the completed version of the application available here: `$COURSE_HOME/session_03/lab_05/complete`

. Navigate a command line window to the root of the .NET project directory (the folder in which files like `project.json` and `appsettings.json` appear).  It is important you are in the correct folder when you push an application from CloudFoundry.

. In this directory, create a new `manifest.yml` file, and set up your deployment metadata using these values.
+
[source,bash]
----
---
applications:
- name: colorservice
  host: colors-${random-word}
  path: .
  buildpack: https://github.com/cloudfoundry-community/asp.net5-buildpack.git
----

. Push the application to Cloud Foundry.
+
[source,bash]
----
cf push
----

. Once the command completes, you can test your application running within Cloud Foundry.  Get the application route, either by using the Apps Manager or executing the `cf apps` command.  Open that route in the browser, and append the API endpoing `api/colors` to the end of the URL.  You should again see your response, 
+
[source,bash]
----
["blue"]
----
+
Your application has used the community ASP.NET v5 Cloud Foundry buildpack to run a .NET application inside a windows container.  That container includes the .NET CoreCLR, and because its running in ubuntu trusty, it is leveraging true container primitives for resource and namespace isolation.  You can scale your application up and down, aggregate its logs through the firehose, and know that it will be monitored and managed by PCF just like any other application.

== Clean up

. Delete the colorservice application
+
[source,bash]
----
cf d colorservice
----

