:compat-mode:
= Lab 8 - Binding to Spring Cloud Services - Getting Started

[abstract]
+
In this lab, we'll deploy a couple of really simple microservices. The first is a RESTful API that has the business logic needed to say Hello to people. The second is a UI that finds out who you are and then says Hello to you.
--

--


== Exploring the applications

. First off, cd into the lab directory
+
----
$ cd $COURSE_HOME/session_05/lab_08/initial/
----

. List the directory, and notice that there are two projects, hello-ui and hello-server
+
----
$ ls -ltr
total 56
-rw-r--r--   1 jrolfe  staff    75 Feb 18 14:39 settings.gradle
-rw-r--r--   1 jrolfe  staff   511 Feb 18 14:39 manifest.yml
-rw-r--r--   1 jrolfe  staff  2404 Feb 18 14:39 gradlew.bat
-rwxr-xr-x   1 jrolfe  staff  5080 Feb 18 14:39 gradlew
drwxr-xr-x   3 jrolfe  staff   102 Feb 18 14:39 gradle
-rwxr-xr-x   1 jrolfe  staff   191 Feb 18 14:39 create-services.sh
-rw-r--r--   1 jrolfe  staff   231 Feb 18 14:39 build.gradle
drwxr-xr-x   4 jrolfe  staff   136 Feb 18 14:46 build
drwxr-xr-x  15 jrolfe  staff   510 Feb 18 14:59 hello-ui
drwxr-xr-x  14 jrolfe  staff   476 Feb 18 14:59 hello-server
----

. The rest of the labs will ask you to edit portions of these two applications.  You may generate eclipse or idea projects using `gradlew.bat eclipse` or `gradlew.bat idea` or you can simply edit the files with the editor of your choice.
+
. In each project, drill down into the src/main/resources directory, and open up `bootstrap.yml` - notice that we've registered a logical name for each application here.
+
. Build both projects.
+
----
$ cd $COURSE_HOME/session_05/lab_08/initial/
$ gradlew.bat assemble
----
+
. Open the manifest.yml file, and notice how we can push both applications from a single manifest.  Update the values for CF_TARGET, if necessary, to point to the Cloud Foundry instance you are using for this workshop.  (For example, you may need to change pcf10 to pcf5 in the hostname string)
+
. Push the applications
+
----
$ cf push
----
+
. Once both applications are up and running, visit the URL of the UI application, and notice that it complains with a hard coded greeting.  These two microservices aren't connected at all!  In the next lab, we'll use Spring Cloud Services to fix that.
